# Generated by Django 4.1.1 on 2022-10-06 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="icon",
            field=models.ImageField(null=True, upload_to="portfolio/icon/"),
        ),
    ]
