# Generated by Django 4.1.1 on 2022-10-06 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_project_icon"),
    ]

    operations = [
        migrations.RemoveField(model_name="project", name="icon",),
        migrations.CreateModel(
            name="Icons",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("icon", models.ImageField(null=True, upload_to="portfolio/icon/")),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="portfolio.project",
                    ),
                ),
            ],
        ),
    ]
