# Generated by Django 4.1.1 on 2022-10-06 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_remove_project_icon_icons"),
    ]

    operations = [
        migrations.RenameModel(old_name="Icons", new_name="Icon",),
    ]
