# Generated by Django 4.1.1 on 2022-10-06 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_rename_icons_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="type_proyect",
            field=models.IntegerField(choices=[(1, "Pagina"), (2, "App")], null=True),
        ),
        migrations.AlterField(
            model_name="icon",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="icons",
                to="portfolio.project",
            ),
        ),
    ]
