# Generated by Django 4.1.1 on 2022-10-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0005_project_type_proyect_alter_icon_project"),
    ]

    operations = [
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=20)),
                ("last_name", models.CharField(max_length=20)),
                ("profession", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
                ("photo", models.ImageField(null=True, upload_to="portfolio/profile/")),
                (
                    "favicon",
                    models.ImageField(
                        null=True, upload_to="portfolio/profile/favicon/"
                    ),
                ),
                ("descripttion_name", models.CharField(max_length=200)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                (
                    "cv_english",
                    models.FileField(null=True, upload_to="portfolio/cv/english/"),
                ),
                (
                    "cv_spanish",
                    models.FileField(null=True, upload_to="portfolio/cv/spanis/"),
                ),
                (
                    "cv_french",
                    models.FileField(null=True, upload_to="portfolio/cv/french/"),
                ),
                ("descripttion_app", models.CharField(max_length=2000)),
                ("descripttion_web", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skills", models.ImageField(null=True, upload_to="portfolio/skills/")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="portfolio.profile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flags", models.ImageField(null=True, upload_to="portfolio/flags/")),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="portfolio.profile",
                    ),
                ),
            ],
        ),
    ]
