# Generated by Django 4.1.1 on 2022-10-08 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_rename_flags_flag_flag_rename_skills_skill_skill_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project", name="date", field=models.DateField(null=True),
        ),
    ]
