# Generated by Django 4.1.1 on 2022-10-08 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_project_date"),
    ]

    operations = [
        migrations.RemoveField(model_name="profile", name="descripttion_name",),
    ]
