# Generated by Django 4.1.1 on 2022-10-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0009_remove_profile_descripttion_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="descripttion_name",
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
